"""Plain-text renderer — shows exactly what a naive ATS parser would see."""

from __future__ import annotations

from .layout import contact_line, language_line, present_sections, training_line
from .models import ResumeModel


def _experience_block(exp) -> list[str]:
    lines: list[str] = []
    if exp.condensed:
        meta = " — ".join(
            p for p in [exp.engagement_label, exp.meta_right] if p
        )
        lines.append(f"{exp.title}, {exp.company} — {meta}")
        return lines
    lines.append(exp.title)
    sub = " — ".join(
        p for p in [exp.company, exp.engagement_label, exp.location] if p
    )
    lines.append(sub)
    lines.append(exp.meta_right)
    for b in exp.bullets:
        lines.append(f"  - {b}")
    return lines


def render_txt(resume: ResumeModel) -> str:
    out: list[str] = []
    out.append(resume.name)
    headline = resume.headline
    if resume.tagline:
        headline += f"  |  {resume.tagline}"
    out.append(headline)
    out.append(contact_line(resume))
    out.append("")

    for key, title in present_sections(resume):
        out.append("=" * 60)
        out.append(title.upper())
        out.append("=" * 60)
        if key == "summary":
            out.append(resume.summary)
        elif key == "skills":
            for g in resume.skill_groups:
                out.append(f"{g.name}: {', '.join(g.items)}")
        elif key == "experience":
            for i, exp in enumerate(resume.experiences):
                if i:
                    out.append("")
                out.extend(_experience_block(exp))
        elif key == "projects":
            for i, proj in enumerate(resume.featured_projects):
                if i:
                    out.append("")
                out.append(proj.name)
                out.append(proj.label)
                if proj.tagline:
                    out.append(proj.tagline)
                for b in proj.bullets:
                    out.append(f"  - {b}")
        elif key == "certifications":
            for c in resume.certifications:
                out.append(_fmt_generic(c))
        elif key == "training":
            for g in resume.training:
                out.append(training_line(g))
        elif key == "languages":
            for item in resume.languages:
                out.append(language_line(item))
        elif key == "education":
            for e in resume.education:
                out.append(_fmt_generic(e))
        out.append("")

    out.append("-" * 60)
    out.append(
        f"Generated by resume-as-code · profile: {resume.profile_name}"
        + (f" · target: {resume.target}" if resume.target else "")
    )
    out.append(f"Canonical fingerprint: {resume.canonical_hash}")
    return "\n".join(out).rstrip() + "\n"


def _fmt_generic(item: dict) -> str:
    return " · ".join(str(v) for v in item.values() if v)
